"""Generate the crate-level plugin aggregator for an engine that registers
plugins programmatically (Bevy-style).

The aggregator is a single source file that imports every `impl Plugin for X`
found in the crate and exposes a `pub fn add_all(app: &mut App) -> &mut App`
which registers them all in deterministic order. `main.rs` and integration
tests like `app_smoke.rs` then become thin wrappers that call `add_all` once,
instead of enumerating 80+ plugins by hand. This closes the drift where a new
leaf module landed and silently left the entrypoint files behind.

Engine-agnostic by being opt-in via `chosen_engine.entrypoint`:

- An engine that registers plugins differently (Godot scenes, Unity prefabs)
  simply omits the block; this module is then never invoked.
- The file path, chunk size, and aggregator module name are all data, so an
  engine that uses Bevy idioms but a different layout adjusts via config.

The generator is mechanical: it greps `impl Plugin for X` from every `*.rs`
under `<game>/src/`, derives each plugin's crate-relative module path from
its file location, deduplicates by struct name, sorts deterministically, and
writes the file with a banner that warns against hand-edits.

Author of the entrypoint binary itself (e.g. `main.rs`) is intentionally NOT
generated here in this first pass: an existing user-authored `main.rs` is
preserved verbatim. A future iteration may grow a codegen step that runs only
when `main.rs` is absent, gated behind a separate llm-mode flag.
"""

from __future__ import annotations

import re
from collections.abc import Iterable
from pathlib import Path

# Captures `impl Plugin for FooPlugin {` and `impl Plugin for FooPlugin<X> {`.
# Bevy convention: every plugin struct is a top-level type in the file it lives
# in, so the file path is enough to derive its module path.
_PLUGIN_RE = re.compile(r"^impl\s+Plugin\s+for\s+([A-Z][A-Za-z0-9_]*)\b", re.MULTILINE)

# Banner is written into the generated file. It must survive a Windows / Unix
# round trip (LF/CRLF) without trailing-whitespace lint flags.
_BANNER = (
    "// AUTO-GENERATED by phase2/entrypoint.py. Do not edit by hand.\n"
    "// Regenerated at the end of every loop_driver.py run from the set of\n"
    "// `impl Plugin for X` declarations found under src/. Hand-edits will be\n"
    "// overwritten on the next run; add or remove plugins by writing the\n"
    "// corresponding leaf modules instead.\n"
)


def _module_path_for(rs_file: Path, src_root: Path) -> str:
    """Derive a crate-relative module path from a file path under ``src/``.

    `game/src/buildings/farm.rs` → `crate::buildings::farm`.
    `game/src/sim.rs` → `crate::sim`.
    `game/src/buildings/mod.rs` → `crate::buildings` (aggregator file, not a
    plugin location but handled defensively in case the regex hits one).
    """
    rel = rs_file.relative_to(src_root).with_suffix("")
    parts = list(rel.parts)
    if parts and parts[-1] == "mod":
        parts.pop()
    return "::".join(["crate", *parts])


def find_plugins(
    game_dir: Path,
    excluded: dict | None = None,
) -> list[tuple[str, str]]:
    """Scan `game_dir/src/` for plugin declarations.

    Returns a list of `(plugin_struct_name, module_path)` tuples, deduplicated
    by struct name and sorted by struct name for deterministic output. The
    aggregator file itself (if it already exists) is skipped to avoid a
    self-reference cycle and to keep regeneration idempotent.

    ``excluded`` is an optional ``{plugin_name: reason}`` mapping from
    `entrypoint_config.excluded_plugins`. Excluded plugins are still on disk
    (the loop driver's revert + repair loop owns regenerating them) but are
    held out of the aggregator so the binary and smoke test can run while the
    broken module is being fixed. Drop entries from the map once the plugin is
    regenerated and the smoke test passes.
    """
    src_root = game_dir / "src"
    if not src_root.is_dir():
        return []
    excluded_names = set(excluded or {})

    found: dict[str, str] = {}
    for rs_file in sorted(src_root.rglob("*.rs")):
        if rs_file.name == "main.rs":
            continue
        try:
            text = rs_file.read_text(encoding="utf-8")
        except OSError:
            continue
        for match in _PLUGIN_RE.finditer(text):
            name = match.group(1)
            if name in excluded_names:
                continue
            # First file wins on duplicate names — deterministic with the sort.
            found.setdefault(name, _module_path_for(rs_file, src_root))
    return sorted(found.items())


def _chunk(items: list[str], size: int) -> Iterable[list[str]]:
    """Yield successive chunks of `size`. Bevy's `add_plugins` accepts tuples
    of up to 15 elements; chunking lets the generator stay under that limit.
    """
    size = max(1, size)
    for i in range(0, len(items), size):
        yield items[i : i + size]


def render_aggregator(plugins: list[tuple[str, str]], chunk_size: int = 14) -> str:
    """Render the full `app_plugins.rs` source for the given plugin list.

    The output has three sections: imports (one `use` per plugin), the
    function signature `pub fn add_all(app: &mut App) -> &mut App`, and a
    chained `.add_plugins(( ... ))` call per chunk. When `plugins` is empty
    the function still compiles — it is a no-op that returns `app` unchanged.
    The whole chained sequence is the function's trailing expression; no
    trailing `;` is emitted so the `&mut App` return value flows out.
    """
    imports = [f"use {module}::{name};" for name, module in plugins]
    chunks = list(_chunk([name for name, _ in plugins], chunk_size))

    body_lines: list[str] = []
    for chunk in chunks:
        if len(chunk) == 1:
            body_lines.append(f"        .add_plugins({chunk[0]})")
        else:
            inner = ", ".join(chunk)
            body_lines.append(f"        .add_plugins(({inner}))")

    parts: list[str] = [
        _BANNER,
        "",
        "use bevy::prelude::*;",
        "",
        *imports,
        "",
        "/// Register every plugin discovered under `src/`.",
        "///",
        "/// Generated by `phase2/entrypoint.py` at the end of each loop_driver",
        "/// run. The caller still owns `DefaultPlugins`, window config, camera",
        "/// spawning, and any per-engine resources that vary per binary.",
        "pub fn add_all(app: &mut App) -> &mut App {",
    ]
    # The whole `app .add_plugins(...) .add_plugins(...)` block is one
    # trailing expression — no `;` on any line.
    parts.append("    app")
    parts.extend(body_lines)
    parts.append("}")
    parts.append("")
    return "\n".join(parts)


def regenerate_aggregator(game_dir: Path, entrypoint_config: dict | None) -> Path | None:
    """Write `app_plugins.rs` according to `entrypoint_config`; return its path.

    Returns `None` and is a no-op when:
    - `entrypoint_config` is `None` (engine doesn't opt in), or
    - `aggregator_file` is missing from the config.

    Writes are atomic-ish: the file is overwritten unconditionally when the
    rendered text differs from disk, so the timestamp only moves on real
    content changes (keeps Cargo's incremental build fast on no-op runs).
    """
    if not entrypoint_config:
        return None
    rel = entrypoint_config.get("aggregator_file")
    if not rel:
        return None

    chunk_size = int(entrypoint_config.get("tuple_chunk_size", 14))
    target = game_dir / rel
    plugins = find_plugins(game_dir, excluded=entrypoint_config.get("excluded_plugins"))
    rendered = render_aggregator(plugins, chunk_size=chunk_size)

    if target.exists():
        try:
            current = target.read_text(encoding="utf-8")
        except OSError:
            current = ""
        if current == rendered:
            return target

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(rendered, encoding="utf-8")
    return target
