"""Phase 2 loop driver: iterate a list of goals through codegen + cargo build.

One step up from ``phase2/driver.py``, which runs one goal and writes one file.
The loop driver runs *N* goals and lets the LLM emit a *multi-file* tree, then
gates each turn behind ``cargo build game/``. On a build failure, every file
written this turn is reverted (restoring prior content or deleting newly
created files) and the goal is recorded as ``pending``.

CLI::

    python phase2/loop_driver.py "implement the ranger unit" "implement the harpy"
    python phase2/loop_driver.py --goals-file phase2/goals.txt
    python phase2/loop_driver.py --dry-run "implement the ranger unit"

The goals-file format is one entry per line. Lines starting with ``#`` are
comments. A line may carry an explicit note_id with ``id|goal text``::

    # weapons
    ranger|implement the ranger unit
    harpy|implement the harpy infected unit

Per-goal flow inside one turn:

1. Call ``codegen.generate(goal)``.
2. If the response misses or hallucinates a ``// Sources:`` header,
   record pending and continue.
3. Parse the response into ``[(rel_path, content)]`` pairs.
4. Merge into ``game/`` (backing up replaced files). ``Cargo.toml`` and
   ``Cargo.lock`` are skipped so the regression-anchor deps stay pinned.
5. Run ``cargo build`` in ``game/``. On non-zero exit, revert the merge
   and record pending. On success, ``record_implementation`` with the
   list of files written.
6. After the loop, ``cap_tokens`` + persist ``build/system_map.yaml``.

Stops on the first ``--error-budget`` failures (default 3) so a broken
prompt does not burn the whole queue.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT / "phase2") not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT / "phase2"))

import codegen  # noqa: E402
import system_map  # noqa: E402

DEFAULT_GAME_DIR = _REPO_ROOT / "game"
DEFAULT_ERROR_BUDGET = 3

_FILE_BLOCK_RE = re.compile(
    r"^=== FILE:[ \t]*(?P<path>.+?)[ \t]*===[ \t]*$\n(?P<content>.*?)\n=== END FILE ===",
    re.DOTALL | re.MULTILINE,
)

# Files we never overwrite from LLM output. Dep pins live in the regression
# anchor; Cargo.lock is regenerated by cargo itself.
_OVERWRITE_SKIPLIST: frozenset[str] = frozenset({"Cargo.toml", "Cargo.lock"})

# "implement the <slug>" / "implement <slug>" — slug is the leading token.
_NOTE_ID_RE = re.compile(r"implement(?:\s+the)?\s+(?P<slug>[a-z0-9_-]+)", re.IGNORECASE)

_GOAL_LINE_SEPARATOR = "|"


def parse_codegen_output(text: str) -> list[tuple[str, str]]:
    """Extract ``(path, content)`` pairs from codegen output.

    The codegen prompt (engine baseline "File output format") instructs the
    model to wrap each file in ``=== FILE: <path> ===`` / ``=== END FILE ===``
    markers with raw content between them. Returns the ordered list of
    (relative_path, file_content) tuples. Empty list if no blocks parse —
    callers treat that as a turn failure (the model ignored the contract).
    """
    return [(m.group("path"), m.group("content")) for m in _FILE_BLOCK_RE.finditer(text)]


def _normalize_rel_path(raw: str, crate_dir_name: str) -> str:
    """Strip stray leading slashes and a redundant crate-dir prefix.

    The contract says paths are relative to the crate root, but the model
    sometimes prefixes the crate directory (``game/src/...``). Strip it so the
    file lands at ``game/src/...`` rather than ``game/game/src/...``.
    """
    rel = raw.strip().lstrip("/")
    prefix = f"{crate_dir_name}/"
    if rel.startswith(prefix):
        rel = rel[len(prefix) :]
    return rel


def derive_note_id(goal: str) -> str:
    """Pull a vault-style slug out of an ``implement the X ...`` goal.

    Falls back to a slug of the goal text (up to 40 chars) when the pattern
    does not match, so the system_map entry still has something to key on.
    """
    match = _NOTE_ID_RE.search(goal)
    if match:
        return match.group("slug").lower()
    return re.sub(r"\W+", "_", goal.lower()).strip("_")[:40]


@dataclass
class WrittenFile:
    """One entry in a turn's merge trail; used to revert on cargo failure.

    ``prior_bytes`` holds the exact original file content (when it existed) so a
    revert restores it byte-for-byte, including line endings. Decoding to text
    and re-writing would flip CRLF/LF and leave the file dirty in git.
    """

    path: Path
    existed_before: bool
    prior_bytes: bytes | None


@dataclass
class TurnResult:
    """One iteration's outcome; aggregated by ``run_loop`` for reporting."""

    note_id: str
    goal: str
    status: str  # implemented | pending | skipped
    files_written: list[str] = field(default_factory=list)
    files_skipped: list[str] = field(default_factory=list)
    error: str | None = None


def merge_into_game(
    parsed: list[tuple[str, str]],
    game_dir: Path,
    skiplist: frozenset[str] = _OVERWRITE_SKIPLIST,
) -> tuple[list[WrittenFile], list[str]]:
    """Write ``parsed`` files into ``game_dir`` with backups for revert.

    Returns ``(written, skipped)``: ``written`` is the trail of files
    touched on disk (for ``revert_merge``), ``skipped`` lists files left
    untouched because they appear in ``skiplist``.
    """
    written: list[WrittenFile] = []
    skipped: list[str] = []
    for raw_rel, content in parsed:
        rel = _normalize_rel_path(raw_rel, game_dir.name)
        if rel in skiplist:
            skipped.append(rel)
            continue
        target = game_dir / rel
        existed = target.exists()
        prior = target.read_bytes() if existed else None
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        written.append(WrittenFile(target, existed, prior))
    return written, skipped


def revert_merge(written: list[WrittenFile]) -> None:
    """Restore the prior on-disk state captured by ``merge_into_game``.

    Existing files are rewritten from their exact prior bytes; files created
    this turn are deleted. Either way the tree returns to its pre-turn state.
    """
    for entry in written:
        if entry.existed_before and entry.prior_bytes is not None:
            entry.path.write_bytes(entry.prior_bytes)
        else:
            entry.path.unlink(missing_ok=True)


def _resolve_cargo() -> str | None:
    """Find the cargo binary on PATH, else in the default rustup location.

    rustup installs to ``~/.cargo/bin`` and adds it to the user PATH via the
    registry, but a shell that started before the install (or a subprocess
    inheriting a stale PATH) will not see it. Fall back to the well-known
    location so the loop driver works without a shell restart.
    """
    found = shutil.which("cargo")
    if found:
        return found
    name = "cargo.exe" if os.name == "nt" else "cargo"
    candidate = Path.home() / ".cargo" / "bin" / name
    return str(candidate) if candidate.exists() else None


def run_cargo_build(
    game_dir: Path,
    cargo_bin: Path | None = None,
) -> tuple[bool, str]:
    """Run ``cargo build`` in ``game_dir``; return ``(success, combined_output)``.

    Resolves cargo via ``_resolve_cargo`` (PATH, then ``~/.cargo/bin``) unless
    ``cargo_bin`` is supplied. If cargo cannot be found the call returns a
    falsey result with an explanatory message rather than raising, so the loop
    driver records it as a normal turn failure.
    """
    cargo = str(cargo_bin) if cargo_bin is not None else _resolve_cargo()
    if cargo is None:
        return False, "cargo not found on PATH or in ~/.cargo/bin (rustup install required)"
    result = subprocess.run(
        [cargo, "build", "--quiet"],
        cwd=str(game_dir),
        capture_output=True,
        text=True,
        check=False,
    )
    return result.returncode == 0, (result.stdout or "") + (result.stderr or "")


def parse_goal_line(line: str) -> tuple[str | None, str]:
    """Split ``id|goal`` lines into ``(id_or_None, goal_text)``."""
    if _GOAL_LINE_SEPARATOR in line:
        head, tail = line.split(_GOAL_LINE_SEPARATOR, 1)
        head = head.strip()
        tail = tail.strip()
        return (head or None), tail
    return None, line.strip()


def load_goals(
    goals_file: Path | None,
    positional: list[str],
) -> list[tuple[str | None, str]]:
    """Resolve the goal list, preferring CLI args over the file.

    Returns ``[(explicit_note_id_or_None, goal_text)]``. Comments and
    blank lines in the file are skipped.
    """
    if positional:
        return [parse_goal_line(g) for g in positional]
    if goals_file is not None and goals_file.exists():
        out: list[tuple[str | None, str]] = []
        for raw in goals_file.read_text(encoding="utf-8").splitlines():
            stripped = raw.strip()
            if not stripped or stripped.startswith("#"):
                continue
            out.append(parse_goal_line(stripped))
        return out
    return []


def already_implemented(state: dict[str, Any], note_id: str) -> bool:
    """True if any ``implemented`` entry already has this note_id."""
    return any(impl.get("id") == note_id for impl in state.get("implemented", []))


def _sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _dump_turn_output(note_id: str, text: str, out_dir: Path) -> None:
    """Persist a turn's raw codegen output to ``out_dir/<note_id>.md``.

    A breadcrumb for inspecting what the model produced, especially when a
    turn fails source-header validation or cargo build (the failure branches
    otherwise discard the text). ``out_dir`` is derived from the state path so
    it lands under ``build/`` in production and under the tmp dir in tests.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / f"{note_id}.md").write_text(text, encoding="utf-8")


def _process_goal(
    note_id: str,
    goal: str,
    state: dict[str, Any],
    *,
    game_dir: Path,
    llm_mode: str,
    model: str | None,
    baseline_path: Path,
    generate: Any,
    cargo_runner: Any,
    turn_output_dir: Path,
) -> TurnResult:
    """Run one codegen turn end-to-end. Mutates ``state`` in place."""
    summary = generate(goal, llm_mode=llm_mode, model=model, baseline_path=baseline_path)
    _dump_turn_output(note_id, summary["response_text"], turn_output_dir)
    if not summary["sources_header_ok"]:
        offending = summary["sources_header_offending"] or ["missing_sources_header"]
        system_map.record_pending(state, note_id, offending)
        return TurnResult(note_id, goal, status="pending", error="invalid_source_header")

    parsed = parse_codegen_output(summary["response_text"])
    if not parsed:
        system_map.record_pending(state, note_id, ["no_file_blocks_in_output"])
        return TurnResult(note_id, goal, status="pending", error="no_file_blocks")

    written, skipped = merge_into_game(parsed, game_dir)
    ok, build_output = cargo_runner(game_dir)
    if not ok:
        revert_merge(written)
        system_map.record_pending(state, note_id, ["cargo_build_failed"])
        return TurnResult(
            note_id,
            goal,
            status="pending",
            files_skipped=skipped,
            error=f"cargo_build_failed: {build_output.strip()[:240]}",
        )

    sources = ",".join(codegen.extract_source_paths(summary["response_text"]))
    file_list = ";".join(
        str(entry.path.relative_to(game_dir)).replace("\\", "/") for entry in written
    )
    system_map.record_implementation(
        state,
        note_id=note_id,
        file=file_list,
        sha=_sha256(summary["response_text"]),
        verified_against=sources,
    )
    return TurnResult(
        note_id,
        goal,
        status="implemented",
        files_written=[
            str(entry.path.relative_to(game_dir)).replace("\\", "/") for entry in written
        ],
        files_skipped=skipped,
    )


def run_loop(
    goals: list[tuple[str | None, str]],
    *,
    game_dir: Path = DEFAULT_GAME_DIR,
    state_path: Path = system_map.DEFAULT_PATH,
    baseline_path: Path = codegen.DEFAULT_BASELINE_PATH,
    llm_mode: str = codegen.DEFAULT_LLM_MODE,
    model: str | None = None,
    error_budget: int = DEFAULT_ERROR_BUDGET,
    generate: Any = codegen.generate,
    cargo_runner: Any = run_cargo_build,
) -> list[TurnResult]:
    """Drive ``goals`` through the codegen + cargo loop. Persists state once at end."""
    state = system_map.load_state(state_path)
    turn_output_dir = state_path.parent / "turns"
    results: list[TurnResult] = []
    errors = 0
    for explicit_id, goal in goals:
        note_id = explicit_id or derive_note_id(goal)
        if already_implemented(state, note_id):
            results.append(TurnResult(note_id, goal, status="skipped"))
            continue
        result = _process_goal(
            note_id,
            goal,
            state,
            game_dir=game_dir,
            llm_mode=llm_mode,
            model=model,
            baseline_path=baseline_path,
            generate=generate,
            cargo_runner=cargo_runner,
            turn_output_dir=turn_output_dir,
        )
        results.append(result)
        if result.status == "pending":
            errors += 1
            if errors >= error_budget:
                break
    state = system_map.cap_tokens(state)
    system_map.save_state(state_path, state)
    return results


def _format_result(result: TurnResult) -> str:
    marker = {"implemented": "OK  ", "pending": "FAIL", "skipped": "SKIP"}[result.status]
    line = f"[{marker}] {result.note_id}: {result.goal}"
    if result.files_written:
        line += f"  -> {len(result.files_written)} files"
    if result.files_skipped:
        line += f"  (skipped: {','.join(result.files_skipped)})"
    if result.error:
        line += f"  ({result.error[:120]})"
    return line


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("goals", nargs="*", help="goals as positional args ('id|text' allowed)")
    parser.add_argument(
        "--goals-file",
        type=Path,
        default=None,
        help="path to a goals file, one entry per line ('id|goal text' or 'goal text')",
    )
    parser.add_argument(
        "--error-budget",
        type=int,
        default=DEFAULT_ERROR_BUDGET,
        help="stop after this many consecutive turns route to pending (default: 3)",
    )
    parser.add_argument(
        "--llm-mode",
        default=codegen.DEFAULT_LLM_MODE,
        choices=codegen.LLM_MODES,
    )
    parser.add_argument("--model", default=None)
    parser.add_argument("--game-dir", type=Path, default=DEFAULT_GAME_DIR)
    parser.add_argument("--state-path", type=Path, default=system_map.DEFAULT_PATH)
    parser.add_argument("--baseline", type=Path, default=codegen.DEFAULT_BASELINE_PATH)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")

    goals = load_goals(args.goals_file, args.goals)
    if not goals:
        print("error: no goals (pass positional args or --goals-file)", file=sys.stderr)
        return 2

    results = run_loop(
        goals,
        game_dir=args.game_dir,
        state_path=args.state_path,
        baseline_path=args.baseline,
        llm_mode=args.llm_mode,
        model=args.model,
        error_budget=args.error_budget,
    )

    counts: dict[str, int] = {}
    for r in results:
        counts[r.status] = counts.get(r.status, 0) + 1
        print(_format_result(r))
    print(f"\nsummary: {counts}")
    return 0 if counts.get("pending", 0) == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
