"""Phase 2 loop driver: iterate a list of goals through codegen + cargo build.

One step up from ``phase2/driver.py``, which runs one goal and writes one file.
The loop driver runs *N* goals and lets the LLM emit a *multi-file* tree, then
gates each turn behind ``cargo build game/``. On a build failure, every file
written this turn is reverted (restoring prior content or deleting newly
created files) and the goal is recorded as ``pending``.

CLI::

    python phase2/loop_driver.py "implement the ranger unit" "implement the harpy"
    python phase2/loop_driver.py --goals-file phase2/goals.txt
    python phase2/loop_driver.py --dry-run "implement the ranger unit"

The goals-file format is one entry per line. Lines starting with ``#`` are
comments. A line may carry an explicit note_id with ``id|goal text``::

    # weapons
    ranger|implement the ranger unit
    harpy|implement the harpy infected unit

Per-goal flow inside one turn:

1. Call ``codegen.generate(goal)``.
2. If the response misses or hallucinates a ``// Sources:`` header,
   record pending and continue.
3. Parse the response into ``[(rel_path, content)]`` pairs.
4. Merge into ``game/`` (backing up replaced files). ``Cargo.toml`` and
   ``Cargo.lock`` are skipped so the regression-anchor deps stay pinned.
5. Run ``cargo build`` in ``game/``. On non-zero exit, revert the merge
   and record pending. On success, ``record_implementation`` with the
   list of files written.
6. After the loop, persist the complete ``build/system_map.yaml`` ledger
   (the 1k-token cap is applied later, only to the codegen prompt projection).

Stops on the first ``--error-budget`` failures (default 3) so a broken
prompt does not burn the whole queue.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT / "phase2") not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT / "phase2"))

import codegen  # noqa: E402
import entrypoint  # noqa: E402
import system_map  # noqa: E402

DEFAULT_GAME_DIR = _REPO_ROOT / "game"
DEFAULT_GAME_CONFIG = _REPO_ROOT / "game-config.json"
DEFAULT_ERROR_BUDGET = 3

_FILE_BLOCK_RE = re.compile(
    r"^=== FILE:[ \t]*(?P<path>.+?)[ \t]*===[ \t]*$\n(?P<content>.*?)\n=== END FILE ===",
    re.DOTALL | re.MULTILINE,
)

# Files we never overwrite from LLM output. Dep pins live in the regression
# anchor; Cargo.lock is regenerated by cargo itself.
_OVERWRITE_SKIPLIST: frozenset[str] = frozenset({"Cargo.toml", "Cargo.lock"})

# "implement the <slug>" / "implement <slug>" — slug is the leading token.
_NOTE_ID_RE = re.compile(r"implement(?:\s+the)?\s+(?P<slug>[a-z0-9_-]+)", re.IGNORECASE)

_GOAL_LINE_SEPARATOR = "|"


def parse_codegen_output(text: str) -> list[tuple[str, str]]:
    """Extract ``(path, content)`` pairs from codegen output.

    The codegen prompt (engine baseline "File output format") instructs the
    model to wrap each file in ``=== FILE: <path> ===`` / ``=== END FILE ===``
    markers with raw content between them. Returns the ordered list of
    (relative_path, file_content) tuples. Empty list if no blocks parse —
    callers treat that as a turn failure (the model ignored the contract).
    """
    return [(m.group("path"), m.group("content")) for m in _FILE_BLOCK_RE.finditer(text)]


def _normalize_rel_path(raw: str, crate_dir_name: str) -> str:
    """Strip stray leading slashes and a redundant crate-dir prefix.

    The contract says paths are relative to the crate root, but the model
    sometimes prefixes the crate directory (``game/src/...``). Strip it so the
    file lands at ``game/src/...`` rather than ``game/game/src/...``.
    """
    rel = raw.strip().lstrip("/")
    prefix = f"{crate_dir_name}/"
    if rel.startswith(prefix):
        rel = rel[len(prefix) :]
    return rel


def load_module_registration(game_config_path: Path) -> dict[str, str] | None:
    """Read ``chosen_engine.module_registration`` from game-config.json.

    This block is per-engine data: ``{"aggregator": "{dir}/mod.rs",
    "declaration": "pub mod {stem};"}`` for Bevy/Rust. The driver stays engine
    neutral — it renders these templates rather than hard-coding any language
    syntax. Returns None when the file or block is absent (then module
    registration is skipped entirely, the opt-in path for engines that have no
    aggregator-file concept).
    """
    if not game_config_path.exists():
        return None
    config = json.loads(game_config_path.read_text(encoding="utf-8"))
    reg = (config.get("chosen_engine") or {}).get("module_registration")
    if isinstance(reg, dict) and reg.get("aggregator") and reg.get("declaration"):
        return reg
    return None


def load_entrypoint_config(game_config_path: Path) -> dict | None:
    """Read ``chosen_engine.entrypoint`` from game-config.json.

    Opt-in per engine: a block of the shape ``{"aggregator_file":
    "src/app_plugins.rs", "tuple_chunk_size": 14, ...}`` enables app-level
    plugin aggregation (see ``regenerate_app_aggregator``). Returns None when
    the file or block is absent so engines that have no programmatic plugin
    registry skip the step entirely. ``aggregator_file`` is the only required
    key; the rest carry sensible defaults inside the renderer.
    """
    if not game_config_path.exists():
        return None
    config = json.loads(game_config_path.read_text(encoding="utf-8"))
    cfg = (config.get("chosen_engine") or {}).get("entrypoint")
    if isinstance(cfg, dict) and cfg.get("aggregator_file"):
        return cfg
    return None


def aggregator_basename(registration: dict[str, str] | None) -> str | None:
    """Derive the aggregator filename (e.g. ``mod.rs``) from the template.

    Used to skip LLM-emitted aggregator files so the driver owns them instead.
    """
    if not registration:
        return None
    rendered = registration["aggregator"].format(dir="_", stem="_")
    return Path(rendered).name


def crate_root_basename(registration: dict[str, str] | None) -> str | None:
    """Derive the crate-root filename (e.g. ``lib.rs``) from the registration.

    The crate root is a driver-owned aggregator just like ``mod.rs`` — the LLM
    must never emit it (it would clobber the hand-built ``lib.rs`` that wires
    ``sim``, the checksum plugin, and every kind module). Returns None when the
    engine config declares no ``crate_root`` (the opt-in field).
    """
    if not registration or not registration.get("crate_root"):
        return None
    return Path(registration["crate_root"]).name


def derive_note_id(goal: str) -> str:
    """Pull a vault-style slug out of an ``implement the X ...`` goal.

    Falls back to a slug of the goal text (up to 40 chars) when the pattern
    does not match, so the system_map entry still has something to key on.
    """
    match = _NOTE_ID_RE.search(goal)
    if match:
        return match.group("slug").lower()
    return re.sub(r"\W+", "_", goal.lower()).strip("_")[:40]


def derive_kind(goal: str) -> str | None:
    """Return the trailing word of an ``implement the X <kind>`` goal as its kind.

    From-vault goals are ``"implement the <slug words> <kind>"``, so the kind is
    the last whitespace token. This is only a *grouping key* for sibling-exemplar
    reuse, not a vault lookup: it just has to be the same for every goal of one
    kind in a run (it is, since they share the from-vault suffix). Returns None
    when the goal has fewer than two tokens.
    """
    tokens = goal.strip().split()
    if len(tokens) < 2:
        return None
    return tokens[-1].lower()


def _read_leaf_text(game_dir: Path, rels: list[str], note_id: str) -> str | None:
    """Read the exemplar leaf for ``note_id`` from a list of relative paths.

    Prefers the file whose stem matches ``note_id`` (the module's own leaf),
    else the first path. Empty entries are ignored. Returns the on-disk text, or
    None when nothing readable is found (a stale or directory path).
    """
    candidates = [r for r in rels if r]
    if not candidates:
        return None
    chosen = next((r for r in candidates if Path(r).stem == note_id), candidates[0])
    target = game_dir / chosen
    if not target.is_file():
        return None
    return target.read_text(encoding="utf-8")


@dataclass
class WrittenFile:
    """One entry in a turn's merge trail; used to revert on cargo failure.

    ``prior_bytes`` holds the exact original file content (when it existed) so a
    revert restores it byte-for-byte, including line endings. Decoding to text
    and re-writing would flip CRLF/LF and leave the file dirty in git.
    """

    path: Path
    existed_before: bool
    prior_bytes: bytes | None


@dataclass
class TurnResult:
    """One iteration's outcome; aggregated by ``run_loop`` for reporting."""

    note_id: str
    goal: str
    status: str  # implemented | pending | skipped
    files_written: list[str] = field(default_factory=list)
    files_skipped: list[str] = field(default_factory=list)
    error: str | None = None


def merge_into_game(
    parsed: list[tuple[str, str]],
    game_dir: Path,
    skiplist: frozenset[str] = _OVERWRITE_SKIPLIST,
    aggregator_name: str | None = None,
    crate_root_name: str | None = None,
) -> tuple[list[WrittenFile], list[str]]:
    """Write ``parsed`` leaf files into ``game_dir`` with backups for revert.

    Returns ``(written, skipped)``: ``written`` is the trail of files touched
    on disk (for ``revert_merge``), ``skipped`` lists files left untouched.
    Skips files in ``skiplist`` (dep pins) and any file whose basename matches
    ``aggregator_name`` (e.g. ``mod.rs``) or ``crate_root_name`` (e.g. ``lib.rs``)
    — those are driver-owned and edited by ``register_modules`` so the LLM
    cannot drop shared declarations or clobber the crate root.
    """
    owned = {n for n in (aggregator_name, crate_root_name) if n}
    written: list[WrittenFile] = []
    skipped: list[str] = []
    for raw_rel, content in parsed:
        rel = _normalize_rel_path(raw_rel, game_dir.name)
        if rel in skiplist or Path(rel).name in owned:
            skipped.append(rel)
            continue
        target = game_dir / rel
        existed = target.exists()
        prior = target.read_bytes() if existed else None
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        written.append(WrittenFile(target, existed, prior))
    return written, skipped


def _ensure_declaration(aggregator_path: Path, declaration: str) -> None:
    """Append ``declaration`` as its own line to the aggregator if not present.

    Idempotent and byte-preserving: reads the existing bytes, matches the file's
    newline style, and appends only when the exact line is absent. Editing
    rather than regenerating is the whole point — shared declarations already in
    the aggregator (marker types, sibling modules) are left untouched.
    """
    decl_bytes = declaration.encode("utf-8")
    if aggregator_path.exists():
        raw = aggregator_path.read_bytes()
        newline = b"\r\n" if b"\r\n" in raw else b"\n"
        if decl_bytes in raw.split(newline):
            return
        if raw and not raw.endswith(newline):
            raw += newline
        aggregator_path.write_bytes(raw + decl_bytes + newline)
    else:
        aggregator_path.parent.mkdir(parents=True, exist_ok=True)
        aggregator_path.write_bytes(decl_bytes + b"\n")


def _registration_nodes(
    leaf: Path, game_dir: Path, src_root: Path | None
) -> list[tuple[Path, str]]:
    """Yield ``(parent_dir, module_name)`` pairs to declare for one leaf.

    The first pair declares the leaf file in its own directory. When a
    ``src_root`` (the crate-root file's directory) is known, the chain
    continues upward: each intermediate directory is declared in its parent,
    stopping once a direct child of ``src_root`` has been recorded. Without a
    ``src_root`` only the leaf's own directory is wired (the historical
    behaviour, kept for engines that declare no ``crate_root``).
    """
    nodes: list[tuple[Path, str]] = [(leaf.parent, leaf.stem)]
    if src_root is None:
        return nodes
    current = leaf.parent
    while current != src_root and src_root in current.parents:
        nodes.append((current.parent, current.name))
        current = current.parent
    return nodes


def register_modules(
    leaf_files: list[Path],
    game_dir: Path,
    registration: dict[str, str] | None,
) -> list[WrittenFile]:
    """Declare each leaf module up the chain to the crate root.

    Driver-owned so the LLM never regenerates an aggregator and drops the
    shared declarations a sibling depends on. The aggregator path, declaration,
    and (optional) crate-root file come from per-engine ``module_registration``
    data, so this holds no language literals. Returns a revert trail for every
    aggregator touched (backed up once, before its first edit). No-op when
    ``registration`` is None.

    With ``crate_root`` set, a leaf at ``src/buildings/wood_gate.rs`` wires
    ``pub mod wood_gate;`` into ``src/buildings/mod.rs`` AND ``pub mod buildings;``
    into ``src/lib.rs`` — so introducing a brand-new kind directory no longer
    leaves the module orphaned (which cargo would not flag, giving a false-green
    gate). Without ``crate_root`` only the leaf's own directory is wired, the
    historical behaviour: a leaf directly under the crate root then renders an
    aggregator the root may not use and fails loud via cargo.
    """
    if not registration:
        return []
    agg_tmpl = registration["aggregator"]
    decl_tmpl = registration["declaration"]
    crate_root = registration.get("crate_root")
    crate_root_path = game_dir / crate_root if crate_root else None
    src_root = crate_root_path.parent if crate_root_path else None
    touched: dict[Path, WrittenFile] = {}
    for leaf in leaf_files:
        for parent_dir, module_name in _registration_nodes(leaf, game_dir, src_root):
            fields = {"dir": parent_dir.relative_to(game_dir).as_posix(), "stem": module_name}
            if src_root is not None and parent_dir == src_root:
                agg_path = crate_root_path  # type: ignore[assignment]
            else:
                agg_path = game_dir / agg_tmpl.format(**fields)
            if agg_path == leaf:
                continue
            if agg_path not in touched:
                existed = agg_path.exists()
                prior = agg_path.read_bytes() if existed else None
                touched[agg_path] = WrittenFile(agg_path, existed, prior)
            _ensure_declaration(agg_path, decl_tmpl.format(**fields))
    return list(touched.values())


def regenerate_app_aggregator(
    game_dir: Path,
    entrypoint_config: dict | None,
) -> WrittenFile | None:
    """Rewrite the per-engine app aggregator and return a revert trail entry.

    The aggregator (e.g. ``src/app_plugins.rs`` for Bevy) collects every plugin
    found under ``src/`` into one ``add_all`` function so ``main.rs`` and the
    smoke test never need to enumerate plugins by hand. Regenerated after every
    leaf merge so a newly-landed plugin is visible to the next ``cargo test
    --test app_smoke`` — without this, the smoke gate stops covering new code.

    Returns the ``WrittenFile`` (with prior bytes captured before the write) so
    a build/smoke failure can revert this change byte-exact alongside the leaf
    and the per-kind ``mod.rs`` declarations. Returns ``None`` when the engine
    does not opt in (``entrypoint_config`` is None or missing the file path),
    so non-Bevy engines pay no cost.
    """
    if not entrypoint_config:
        return None
    rel = entrypoint_config.get("aggregator_file")
    if not rel:
        return None
    target = game_dir / rel
    existed = target.exists()
    prior = target.read_bytes() if existed else None
    written_path = entrypoint.regenerate_aggregator(game_dir, entrypoint_config)
    if written_path is None:
        return None
    return WrittenFile(target, existed, prior)


def revert_merge(written: list[WrittenFile]) -> None:
    """Restore the prior on-disk state captured by ``merge_into_game``.

    Existing files are rewritten from their exact prior bytes; files created
    this turn are deleted. Either way the tree returns to its pre-turn state.
    """
    for entry in written:
        if entry.existed_before and entry.prior_bytes is not None:
            entry.path.write_bytes(entry.prior_bytes)
        else:
            entry.path.unlink(missing_ok=True)


def _resolve_cargo() -> str | None:
    """Find the cargo binary on PATH, else in the default rustup location.

    rustup installs to ``~/.cargo/bin`` and adds it to the user PATH via the
    registry, but a shell that started before the install (or a subprocess
    inheriting a stale PATH) will not see it. Fall back to the well-known
    location so the loop driver works without a shell restart.
    """
    found = shutil.which("cargo")
    if found:
        return found
    name = "cargo.exe" if os.name == "nt" else "cargo"
    candidate = Path.home() / ".cargo" / "bin" / name
    return str(candidate) if candidate.exists() else None


def _cargo_env() -> dict[str, str]:
    """Build env for cargo subprocesses: inherit PATH, add RUSTFLAGS=-D warnings.

    ``-D warnings`` turns unused-mut, dead-code, and similar warnings into
    errors so the repair loop catches them before they accumulate. If Bevy
    macro-generated code emits false positives on a fresh dep compile, swap
    to the selective set: ``-W unused -D unused_must_use -D unused_mut -D dead_code``.
    Only the project's own crates recompile each turn (Cargo's incremental
    build), so dep warnings surface only on a cold build.
    """
    env = os.environ.copy()
    env["RUSTFLAGS"] = "-D warnings"
    return env


def run_cargo_build(
    game_dir: Path,
    cargo_bin: Path | None = None,
) -> tuple[bool, str]:
    """Run ``cargo build`` in ``game_dir``; return ``(success, combined_output)``.

    Resolves cargo via ``_resolve_cargo`` (PATH, then ``~/.cargo/bin``) unless
    ``cargo_bin`` is supplied. If cargo cannot be found the call returns a
    falsey result with an explanatory message rather than raising, so the loop
    driver records it as a normal turn failure.
    """
    cargo = str(cargo_bin) if cargo_bin is not None else _resolve_cargo()
    if cargo is None:
        return False, "cargo not found on PATH or in ~/.cargo/bin (rustup install required)"
    result = subprocess.run(
        [cargo, "build", "--quiet"],
        cwd=str(game_dir),
        capture_output=True,
        text=True,
        check=False,
        env=_cargo_env(),
    )
    return result.returncode == 0, (result.stdout or "") + (result.stderr or "")


def run_cargo_smoke(
    game_dir: Path,
    cargo_bin: Path | None = None,
) -> tuple[bool, str]:
    """Run ``cargo test --test app_smoke``; return ``(success, combined_output)``.

    Catches runtime panics that ``cargo build`` cannot see: Bevy B0001
    schedule-ambiguity errors, duplicate resource/event registrations, and
    system-ordering conflicts. When the smoke test panics, the output names the
    conflicting systems and the shared component — exactly the signal the repair
    loop needs to feed back to the LLM for a targeted fix-it turn. Run after
    every turn that compiles, before recording it as implemented.
    """
    cargo = str(cargo_bin) if cargo_bin is not None else _resolve_cargo()
    if cargo is None:
        return False, "cargo not found on PATH or in ~/.cargo/bin (rustup install required)"
    result = subprocess.run(
        [cargo, "test", "--test", "app_smoke"],
        cwd=str(game_dir),
        capture_output=True,
        text=True,
        check=False,
        env=_cargo_env(),
    )
    return result.returncode == 0, (result.stdout or "") + (result.stderr or "")


def parse_goal_line(line: str) -> tuple[str | None, str]:
    """Split ``id|goal`` lines into ``(id_or_None, goal_text)``."""
    if _GOAL_LINE_SEPARATOR in line:
        head, tail = line.split(_GOAL_LINE_SEPARATOR, 1)
        head = head.strip()
        tail = tail.strip()
        return (head or None), tail
    return None, line.strip()


def load_goals(
    goals_file: Path | None,
    positional: list[str],
) -> list[tuple[str | None, str]]:
    """Resolve the goal list, preferring CLI args over the file.

    Returns ``[(explicit_note_id_or_None, goal_text)]``. Comments and
    blank lines in the file are skipped.
    """
    if positional:
        return [parse_goal_line(g) for g in positional]
    if goals_file is not None and goals_file.exists():
        out: list[tuple[str | None, str]] = []
        for raw in goals_file.read_text(encoding="utf-8").splitlines():
            stripped = raw.strip()
            if not stripped or stripped.startswith("#"):
                continue
            out.append(parse_goal_line(stripped))
        return out
    return []


def load_valid_kinds(game_config_path: Path) -> set[str] | None:
    """Read the canonical kind names from ``game-config.json -> kinds``.

    Used to filter a ``--from-vault`` walk to directories that are real kinds.
    The vault can accumulate stale directories from a prior taxonomy (e.g. a
    pre-rename singular ``unit/`` alongside the canonical ``units/``); walking
    those would emit duplicate / stale goals. Returns None when the file or the
    ``kinds`` block is absent (then no kind filtering is applied).

    A kind block with ``codegen: false`` is excluded — that flag marks a kind
    as runtime data (campaign maps, release notes, lore-only) for which Phase 2
    should not generate code. Game-agnostic: any wiki / engine can use the same
    knob to keep data-shaped kinds out of the codegen budget.
    """
    if not game_config_path.exists():
        return None
    config = json.loads(game_config_path.read_text(encoding="utf-8"))
    kinds = config.get("kinds")
    if not isinstance(kinds, dict) or not kinds:
        return None
    code_kinds: set[str] = set()
    for name, data in kinds.items():
        if not isinstance(data, dict):
            code_kinds.add(name)
            continue
        if data.get("codegen", True) is False:
            continue
        code_kinds.add(name)
    return code_kinds


def load_systems(game_config_path: Path) -> list[dict[str, Any]]:
    """Read the gameplay system list from ``chosen_engine.systems`` (preferred)
    or the top-level ``systems`` block (fallback).

    The list is per-game data populated by Phase 0's
    ``propose_gameplay_systems``. Empty list when neither location has a
    populated list, or the config file is missing.
    """
    if not game_config_path.exists():
        return []
    config = json.loads(game_config_path.read_text(encoding="utf-8"))
    chosen = config.get("chosen_engine") or {}
    systems = chosen.get("systems") if isinstance(chosen, dict) else None
    if not isinstance(systems, list) or not systems:
        systems = config.get("systems")
    return [s for s in (systems or []) if isinstance(s, dict) and s.get("name")]


def derive_goals_from_systems(
    systems: list[dict[str, Any]],
    names: list[str] | None = None,
) -> list[tuple[str | None, str]]:
    """Turn the ``chosen_engine.systems`` list into ``(name, goal)`` tuples.

    The goal text is ``"implement the <name> system: <description>"`` so
    the existing ``derive_kind`` regex picks up ``system`` as the kind word
    (which routes the leaf into ``src/system/<name>.rs`` via the existing
    ``module_registration`` mechanism). System-specific guidance — what
    state machine pattern to use, how to wire input — lives in
    ``prompts/engine_determinism/<engine>.md``'s ``## System rules`` section,
    not in the per-turn goal text.
    """
    name_filter = set(names) if names else None
    goals: list[tuple[str | None, str]] = []
    for entry in systems:
        nm = entry.get("name")
        desc = entry.get("description", "")
        if not isinstance(nm, str) or not nm:
            continue
        if name_filter is not None and nm not in name_filter:
            continue
        suffix = f": {desc}" if desc else ""
        goals.append((nm, f"implement the {nm.replace('_', ' ')} system{suffix}"))
    return goals


def derive_goals_from_vault(
    vault_dir: Path,
    kinds: list[str] | None = None,
    valid_kinds: set[str] | None = None,
) -> list[tuple[str | None, str]]:
    """Walk ``vault/<kind>/<slug>.md`` into ``(slug, goal)`` pairs.

    The goal is ``"implement the <slug words> <kind>"``; the slug is used as the
    explicit note_id so the loop's ``already_implemented`` skip works. Sorted by
    path for deterministic ordering. Skips ``_quarantine`` and other ``_``-prefixed
    directories. ``kinds`` optionally restricts to an explicit set of kind-directory
    names. ``valid_kinds`` (from ``game-config.json``) drops directories that are
    not real kinds, so stale leftover dirs from a prior taxonomy never produce
    goals — this makes a bare ``--from-vault`` (all kinds) safe to run hands-off.
    """
    if not vault_dir.exists():
        return []
    goals: list[tuple[str | None, str]] = []
    for md in sorted(vault_dir.glob("*/*.md")):
        kind = md.parent.name
        if kind.startswith("_") or (kinds and kind not in kinds):
            continue
        if valid_kinds is not None and kind not in valid_kinds:
            continue
        slug = md.stem
        goals.append((slug, f"implement the {slug.replace('_', ' ')} {kind}"))
    return goals


def already_implemented(state: dict[str, Any], note_id: str) -> bool:
    """True if any ``implemented`` entry already has this note_id."""
    return any(impl.get("id") == note_id for impl in state.get("implemented", []))


def _sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _dump_turn_output(note_id: str, text: str, out_dir: Path) -> None:
    """Persist a turn's raw codegen output to ``out_dir/<note_id>.md``.

    A breadcrumb for inspecting what the model produced, especially when a
    turn fails source-header validation or cargo build (the failure branches
    otherwise discard the text). ``out_dir`` is derived from the state path so
    it lands under ``build/`` in production and under the tmp dir in tests.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / f"{note_id}.md").write_text(text, encoding="utf-8")


@dataclass
class PreparedTurn:
    """Phase-A result for one goal: codegen output, already validated.

    Produced by ``_prepare_turn`` with no writes to ``state`` or ``game/``, so a
    batch of these can be computed concurrently. ``pending_reason`` is set when
    the turn failed before the gate (backend error, bad source header, no file
    blocks); the serial commit phase then just records it pending.
    """

    note_id: str
    goal: str
    parsed: list[tuple[str, str]] | None = None
    response_text: str = ""
    pending_reason: list[str] | None = None
    error: str | None = None


def _format_backend_error(
    exc: Exception,
    exc2: Exception | None = None,
    fb: str | None = None,
) -> str:
    """Format a backend exception's error message keeping its tail, not its head.

    Backend CLIs (codex, claude -p) prepend a banner (model id, workdir, sandbox,
    session id) to every stderr write. The actual error message — quota hit,
    model unavailable, network blip — sits at the end. A naive ``str(exc)[:240]``
    truncation captures only the banner and discards the diagnostic. This helper
    keeps the last 480 chars of the primary error (and the fallback's, when set)
    so operators and downstream agents see *why* the call failed. Engine-agnostic:
    works on any backend that raises with stderr embedded in the exception text.
    """
    primary_tail = str(exc)[-480:]
    if exc2 is not None and fb is not None:
        fallback_tail = str(exc2)[-240:]
        return f"codegen_error: {primary_tail} | fallback {fb}: {fallback_tail}"[:1000]
    return f"codegen_error: {primary_tail}"[:600]


def _prepare_turn(
    note_id: str,
    goal: str,
    *,
    exemplar: str | None,
    llm_mode: str,
    model: str | None,
    baseline_path: Path,
    generate: Any,
    turn_output_dir: Path,
    game_dir: Path | None = None,
    repair: tuple[str, str] | None = None,
    fallback_llm_mode: str | None = None,
    fallback_model: str | None = None,
) -> PreparedTurn:
    """Run codegen + validate its output. Pure: no ``state`` / ``game/`` writes.

    Safe to run concurrently across goals — there is no shared mutable state
    (``retrieval`` builds its own Chroma client per call). Failures are captured
    as a ``pending_reason`` rather than raised, so one bad turn never aborts a
    parallel batch. ``exemplar`` is the same-kind sibling module passed to the
    codegen prompt as the structural pattern (None for the first of a kind).
    ``repair`` is an ``(build_error, prior_attempt)`` pair for a fix-it turn.
    ``game_dir`` is forwarded to ``codegen.generate`` so the registration manifest
    can be built from the current on-disk state of committed plugin files.

    When ``fallback_llm_mode`` is set and the primary backend raises (a real
    crash, not a model output we can validate), the turn is retried once with
    the fallback mode. This is the engine-agnostic safety net for CLI backends
    that fail at process-init time (e.g. codex 0.133.0's `failed to install
    system skills` error) — a user without coding experience cannot diagnose
    a backend-CLI crash, so the loop transparently switches to the other CLI
    that uses the same subscription auth and continues. The fallback is
    backend-agnostic by construction: it activates on **any** exception from
    the primary backend; the model output contract stays the same.
    """
    try:
        summary = generate(
            goal,
            llm_mode=llm_mode,
            model=model,
            baseline_path=baseline_path,
            exemplar=exemplar,
            repair=repair,
            pin_id=note_id,
            pin_kind=derive_kind(goal),
            game_dir=game_dir,
        )
    except Exception as exc:
        if fallback_llm_mode and fallback_llm_mode != llm_mode:
            try:
                summary = generate(
                    goal,
                    llm_mode=fallback_llm_mode,
                    model=fallback_model,
                    baseline_path=baseline_path,
                    exemplar=exemplar,
                    repair=repair,
                    pin_id=note_id,
                    pin_kind=derive_kind(goal),
                    game_dir=game_dir,
                )
            except Exception as exc2:
                return PreparedTurn(
                    note_id,
                    goal,
                    pending_reason=["codegen_error"],
                    error=_format_backend_error(exc, exc2, fallback_llm_mode),
                )
        else:
            # The backend (claude -p / codex / SDK) can fail transiently — e.g.
            # `claude -p` intermittently exits 1 on a large prompt. A hands-off loop
            # must survive it: record pending (retried on the next run) and let the
            # error budget decide when to stop, rather than crashing the whole run.
            return PreparedTurn(
                note_id,
                goal,
                pending_reason=["codegen_error"],
                error=_format_backend_error(exc),
            )
    _dump_turn_output(note_id, summary["response_text"], turn_output_dir)
    text = summary["response_text"]
    if not summary["sources_header_ok"]:
        offending = summary["sources_header_offending"] or ["missing_sources_header"]
        return PreparedTurn(
            note_id,
            goal,
            response_text=text,
            pending_reason=offending,
            error="invalid_source_header",
        )
    parsed = parse_codegen_output(text)
    if not parsed:
        return PreparedTurn(
            note_id,
            goal,
            response_text=text,
            pending_reason=["no_file_blocks_in_output"],
            error="no_file_blocks",
        )
    return PreparedTurn(note_id, goal, parsed=parsed, response_text=text)


def _prepare_batch(
    batch: list[tuple[str, str, str | None]],
    *,
    concurrency: int,
    llm_mode: str,
    model: str | None,
    baseline_path: Path,
    generate: Any,
    turn_output_dir: Path,
    game_dir: Path | None = None,
    fallback_llm_mode: str | None = None,
    fallback_model: str | None = None,
) -> list[PreparedTurn]:
    """Prepare a batch of ``(note_id, goal, exemplar)`` turns; concurrent when N>1.

    The returned list is in ``batch`` order. Concurrency parallelizes only the
    pure codegen phase (the slow LLM subprocess call); the caller still merges
    and gates serially, so the cargo build and ``system_map`` order stay
    deterministic regardless of ``concurrency``. Each turn carries its own
    resolved ``exemplar`` (same-kind sibling source, or None). ``game_dir`` is
    forwarded to each ``_prepare_turn`` so the registration manifest reflects the
    committed state at chunk-start (all turns in a batch see the same snapshot).

    ``fallback_llm_mode`` (+ optional ``fallback_model``) is forwarded so any
    turn whose primary backend crashes transparently retries on the fallback
    before being recorded pending.
    """
    kw = {
        "llm_mode": llm_mode,
        "model": model,
        "baseline_path": baseline_path,
        "generate": generate,
        "turn_output_dir": turn_output_dir,
        "game_dir": game_dir,
        "fallback_llm_mode": fallback_llm_mode,
        "fallback_model": fallback_model,
    }
    if concurrency <= 1 or len(batch) <= 1:
        return [_prepare_turn(nid, goal, exemplar=ex, **kw) for nid, goal, ex in batch]
    with ThreadPoolExecutor(max_workers=concurrency) as pool:
        futures = [
            pool.submit(_prepare_turn, nid, goal, exemplar=ex, **kw) for nid, goal, ex in batch
        ]
        return [f.result() for f in futures]


def _try_build(
    prepared: PreparedTurn,
    game_dir: Path,
    registration: dict[str, str] | None,
    agg_name: str | None,
    crate_root_name: str | None,
    cargo_runner: Any,
    smoke_runner: Any = None,
    entrypoint_config: dict | None = None,
) -> tuple[bool, list[WrittenFile], list[WrittenFile], str, list[str]]:
    """Merge + register a prepared turn and run the build gate(s), once.

    Returns ``(ok, written, touched, build_output, skipped)``: ``written`` is the
    leaf files (for the implemented record), ``touched`` is leaves + aggregators
    (for revert on failure).

    When ``smoke_runner`` is set, a passing ``cargo build`` is followed by
    ``cargo test --test app_smoke``. A smoke failure is treated identically to a
    build failure — the merged files are reverted and the panic output is returned
    as ``build_output`` so the repair loop can feed it to the LLM.

    When ``entrypoint_config`` opts in, the app-level plugin aggregator is also
    regenerated before the build; its revert entry is appended to ``touched`` so
    a failure restores it byte-exact along with the leaf.
    """
    written, skipped = merge_into_game(
        prepared.parsed, game_dir, aggregator_name=agg_name, crate_root_name=crate_root_name
    )
    registered = register_modules([w.path for w in written], game_dir, registration)
    app_agg = regenerate_app_aggregator(game_dir, entrypoint_config)
    touched_aggregators = registered + ([app_agg] if app_agg is not None else [])
    ok, build_output = cargo_runner(game_dir)
    if ok and smoke_runner is not None:
        smoke_ok, smoke_output = smoke_runner(game_dir)
        if not smoke_ok:
            return False, written, written + touched_aggregators, smoke_output, skipped
    return ok, written, written + touched_aggregators, build_output, skipped


def _record_success(
    prepared: PreparedTurn,
    state: dict[str, Any],
    written: list[WrittenFile],
    game_dir: Path,
    skipped: list[str],
) -> TurnResult:
    """Record an implemented turn in ``state`` and build its TurnResult."""
    rels = [str(w.path.relative_to(game_dir)).replace("\\", "/") for w in written]
    sources = ",".join(codegen.extract_source_paths(prepared.response_text))
    system_map.record_implementation(
        state,
        note_id=prepared.note_id,
        file=";".join(rels),
        sha=_sha256(prepared.response_text),
        verified_against=sources,
    )
    return TurnResult(
        prepared.note_id,
        prepared.goal,
        status="implemented",
        files_written=rels,
        files_skipped=skipped,
    )


def _commit_turn(
    prepared: PreparedTurn,
    state: dict[str, Any],
    *,
    game_dir: Path,
    registration: dict[str, str] | None,
    agg_name: str | None,
    crate_root_name: str | None,
    cargo_runner: Any,
    smoke_runner: Any = None,
    entrypoint_config: dict | None = None,
    repair_fn: Any = None,
    repair_attempts: int = 0,
) -> TurnResult:
    """Merge a prepared turn into ``game/``, gate it on the build, record. Serial.

    Mutates ``state`` and the working tree, so this must run one turn at a time
    (a shared build target cannot gate two merges at once). On a build failure
    the merge is reverted byte-exact, then — if ``repair_fn`` is set and attempts
    remain — the build output is fed back through codegen for a fix-it turn and
    re-gated. This is the engine-agnostic correction path: the build tool's own
    errors drive the repair, so no per-engine rules are needed. After
    ``repair_attempts`` exhausted (or an invalid repair) the turn is recorded
    pending.
    """
    if prepared.pending_reason is not None:
        system_map.record_pending(state, prepared.note_id, prepared.pending_reason)
        return TurnResult(prepared.note_id, prepared.goal, status="pending", error=prepared.error)

    attempt = prepared
    build_output = ""
    skipped: list[str] = []
    for tries in range(repair_attempts + 1):
        ok, written, touched, build_output, skipped = _try_build(
            attempt,
            game_dir,
            registration,
            agg_name,
            crate_root_name,
            cargo_runner,
            smoke_runner,
            entrypoint_config,
        )
        if ok:
            return _record_success(attempt, state, written, game_dir, skipped)
        revert_merge(touched)
        if repair_fn is None or tries >= repair_attempts:
            break
        attempt = repair_fn(attempt.note_id, attempt.goal, attempt.response_text, build_output)
        if attempt.parsed is None:
            break

    system_map.record_pending(state, prepared.note_id, ["cargo_build_failed"])
    return TurnResult(
        prepared.note_id,
        prepared.goal,
        status="pending",
        files_skipped=skipped,
        error=f"cargo_build_failed: {build_output.strip()[:240]}",
    )


def _chunk_end(
    attempts: list[tuple[str, str, str | None]],
    start: int,
    concurrency: int,
    ready_kinds: dict[str, str],
) -> int:
    """End index of the next prep chunk starting at ``start``.

    Caps the chunk at ``concurrency`` and stops before a *second* same-kind turn
    whose kind has no exemplar yet (``ready_kinds`` holds kinds that already do).
    This forces the first module of a kind to be committed (seeding the
    exemplar) before its siblings are prompted, so the sibling-consistency
    mechanism holds even under concurrency. Once a kind is seeded, its siblings
    batch freely up to ``concurrency``.
    """
    end = start
    seen_unready: set[str] = set()
    while end < len(attempts) and (end - start) < concurrency:
        kind = attempts[end][2]
        if kind is not None and kind not in ready_kinds:
            if kind in seen_unready:
                break
            seen_unready.add(kind)
        end += 1
    return end


def _seed_exemplars(
    state: dict[str, Any], goal_kinds: dict[str, str | None], game_dir: Path
) -> dict[str, str]:
    """Build the initial per-kind exemplar map from already-implemented modules.

    Lets a fresh sibling turn follow a module accepted in a *prior* run without
    re-committing the seed this run (e.g. soldier stays implemented and seeds the
    other units). First implemented module per kind wins. Kinds come from this
    run's goals, so the grouping key matches the attempted siblings exactly.
    """
    exemplars: dict[str, str] = {}
    for impl in state.get("implemented", []):
        kind = goal_kinds.get(impl.get("id"))
        if not kind or kind in exemplars:
            continue
        text = _read_leaf_text(game_dir, str(impl.get("file", "")).split(";"), impl.get("id", ""))
        if text:
            exemplars[kind] = text
    return exemplars


def _build_plan(
    goals: list[tuple[str | None, str]],
    state: dict[str, Any],
    goal_kinds: dict[str, str | None],
    max_turns: int | None,
) -> tuple[list[tuple[str, Any, Any, Any]], list[tuple[str, str, str | None]]]:
    """Return ``(plan, attempts)`` for ``goals`` in order.

    ``plan`` interleaves ``("skip", TurnResult, ...)`` and ``("attempt", note_id,
    goal, kind)`` entries so output order matches input order. ``attempts`` is
    just the codegen-bound subset, capped at ``max_turns`` (skips do not count).

    A note_id already implemented OR already attempted earlier in this same run
    is skipped: the same slug can appear under two kinds (e.g. a ``technology_tree``
    note in both ``game_mechanics`` and ``research``), and attempting it twice
    would generate the module twice and write two ledger entries with one id.
    First occurrence wins (goals arrive in deterministic sorted order).
    """
    plan: list[tuple[str, Any, Any, Any]] = []
    attempts: list[tuple[str, str, str | None]] = []
    planned_ids: set[str] = set()
    for explicit_id, goal in goals:
        note_id = explicit_id or derive_note_id(goal)
        kind = goal_kinds.get(note_id)
        if already_implemented(state, note_id) or note_id in planned_ids:
            plan.append(("skip", TurnResult(note_id, goal, status="skipped"), None, None))
            continue
        plan.append(("attempt", note_id, goal, kind))
        attempts.append((note_id, goal, kind))
        planned_ids.add(note_id)
        if max_turns is not None and len(attempts) >= max_turns:
            break
    return plan, attempts


def _capture_exemplar(
    exemplars: dict[str, str],
    result: TurnResult,
    kind: str | None,
    note_id: str,
    game_dir: Path,
) -> None:
    """Record the just-accepted module as the kind's exemplar if none is set yet."""
    if result.status != "implemented" or not kind or kind in exemplars:
        return
    seed = _read_leaf_text(game_dir, result.files_written, note_id)
    if seed:
        exemplars[kind] = seed


def _make_repair_fn(
    *,
    llm_mode: str,
    model: str | None,
    baseline_path: Path,
    generate: Any,
    turn_output_dir: Path,
    game_dir: Path | None = None,
    fallback_llm_mode: str | None = None,
    fallback_model: str | None = None,
) -> Any:
    """Build the codegen-with-build-error closure used by the repair loop.

    Returns ``repair(note_id, goal, prior_text, build_error) -> PreparedTurn``: a
    fresh codegen turn that feeds the failed source + the build tool's output
    back so the model fixes its own output. No exemplar is passed — the prior
    attempt already carries the structure to preserve. Engine-agnostic: the
    correction signal is whatever the build runner emitted. ``game_dir`` is
    forwarded so repair turns also receive the registration manifest.
    ``fallback_llm_mode`` is also forwarded so a repair turn can fall back
    when the primary backend crashes mid-repair.
    """

    def _repair(note_id: str, goal: str, prior_text: str, build_error: str) -> PreparedTurn:
        return _prepare_turn(
            note_id,
            goal,
            exemplar=None,
            llm_mode=llm_mode,
            model=model,
            baseline_path=baseline_path,
            generate=generate,
            turn_output_dir=turn_output_dir,
            game_dir=game_dir,
            repair=(build_error, prior_text),
            fallback_llm_mode=fallback_llm_mode,
            fallback_model=fallback_model,
        )

    return _repair


def run_loop(
    goals: list[tuple[str | None, str]],
    *,
    game_dir: Path = DEFAULT_GAME_DIR,
    state_path: Path = system_map.DEFAULT_PATH,
    baseline_path: Path = codegen.DEFAULT_BASELINE_PATH,
    llm_mode: str = codegen.DEFAULT_LLM_MODE,
    model: str | None = None,
    error_budget: int = DEFAULT_ERROR_BUDGET,
    generate: Any = codegen.generate,
    cargo_runner: Any = run_cargo_build,
    smoke_runner: Any = None,
    registration: dict[str, str] | None = None,
    entrypoint_config: dict | None = None,
    max_turns: int | None = None,
    concurrency: int = 1,
    repair_attempts: int = 0,
    fallback_llm_mode: str | None = None,
    fallback_model: str | None = None,
) -> list[TurnResult]:
    """Drive ``goals`` through the codegen + cargo loop. Persists state once at end.

    ``registration`` is the per-engine ``module_registration`` block (see
    ``load_module_registration``); when None, aggregator management is skipped.
    ``max_turns`` caps how many goals are actually attempted this run; goals
    skipped as already-implemented do not count against it, so ``--limit`` makes
    real forward progress regardless of how much is already done.

    ``concurrency`` (>1) runs the codegen phase of upcoming turns in parallel,
    in lookahead batches of that size, while the merge + cargo gate still runs
    one turn at a time in goal order. So results, ``system_map`` order, and the
    error budget behave identically to the serial path (``concurrency=1``); only
    the LLM wait is overlapped. Wasted calls on an error-budget stop are bounded
    to one batch.

    ``repair_attempts`` (>0) enables the build-error repair loop: a turn whose
    build fails is re-generated up to that many times with the build output fed
    back, before being recorded pending. The repair codegen runs serially in the
    gate phase (failures are the minority), so it does not perturb concurrency.
    """
    state = system_map.load_state(state_path)
    turn_output_dir = state_path.parent / "turns"
    agg_name = aggregator_basename(registration)
    crate_root_name = crate_root_basename(registration)
    concurrency = max(1, concurrency)

    # note_id -> kind for every goal this run; the seed map starts from modules
    # already implemented (so a kept module like soldier seeds its siblings).
    goal_kinds = {(eid or derive_note_id(g)): derive_kind(g) for eid, g in goals}
    exemplars = _seed_exemplars(state, goal_kinds, game_dir)

    # Ordered plan: skips recorded inline (free); attempts are the codegen-bound
    # subset, capped by max_turns.
    plan, attempts = _build_plan(goals, state, goal_kinds, max_turns)

    prep_kw = {
        "concurrency": concurrency,
        "llm_mode": llm_mode,
        "model": model,
        "baseline_path": baseline_path,
        "generate": generate,
        "turn_output_dir": turn_output_dir,
        "game_dir": game_dir,
        "fallback_llm_mode": fallback_llm_mode,
        "fallback_model": fallback_model,
    }
    repair_fn = (
        _make_repair_fn(
            llm_mode=llm_mode,
            model=model,
            baseline_path=baseline_path,
            generate=generate,
            turn_output_dir=turn_output_dir,
            game_dir=game_dir,
            fallback_llm_mode=fallback_llm_mode,
            fallback_model=fallback_model,
        )
        if repair_attempts > 0
        else None
    )
    prepared: dict[int, PreparedTurn] = {}
    next_unprepared = 0
    attempt_seq = 0
    results: list[TurnResult] = []
    errors = 0
    for tag, *rest in plan:
        if tag == "skip":
            results.append(rest[0])
            continue
        note_id, _goal, kind = rest
        if attempt_seq not in prepared:
            end = _chunk_end(attempts, next_unprepared, concurrency, exemplars)
            chunk = [(nid, g, exemplars.get(k)) for nid, g, k in attempts[next_unprepared:end]]
            for offset, prep in enumerate(_prepare_batch(chunk, **prep_kw)):
                prepared[next_unprepared + offset] = prep
            next_unprepared = end
        result = _commit_turn(
            prepared[attempt_seq],
            state,
            game_dir=game_dir,
            registration=registration,
            agg_name=agg_name,
            crate_root_name=crate_root_name,
            cargo_runner=cargo_runner,
            smoke_runner=smoke_runner,
            entrypoint_config=entrypoint_config,
            repair_fn=repair_fn,
            repair_attempts=repair_attempts,
        )
        _capture_exemplar(exemplars, result, kind, note_id, game_dir)
        attempt_seq += 1
        results.append(result)
        if result.status == "pending":
            errors += 1
            if errors >= error_budget:
                break
    # Persist the complete ledger (not the capped projection): already_implemented
    # reads this list to skip finished work, so collapsing it would make the loop
    # re-generate older modules every run and never converge. The 1k-token cap is
    # applied only when codegen renders the Layer-4 block (system_map.render_for_prompt).
    system_map.save_state(state_path, state)
    return results


def _format_result(result: TurnResult) -> str:
    marker = {"implemented": "OK  ", "pending": "FAIL", "skipped": "SKIP"}[result.status]
    line = f"[{marker}] {result.note_id}: {result.goal}"
    if result.files_written:
        line += f"  -> {len(result.files_written)} files"
    if result.files_skipped:
        line += f"  (skipped: {','.join(result.files_skipped)})"
    if result.error:
        line += f"  ({result.error[:120]})"
    return line


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("goals", nargs="*", help="goals as positional args ('id|text' allowed)")
    parser.add_argument(
        "--goals-file",
        type=Path,
        default=None,
        help="path to a goals file, one entry per line ('id|goal text' or 'goal text')",
    )
    parser.add_argument(
        "--error-budget",
        type=int,
        default=DEFAULT_ERROR_BUDGET,
        help="stop after this many consecutive turns route to pending (default: 3)",
    )
    parser.add_argument(
        "--llm-mode",
        default=codegen.DEFAULT_LLM_MODE,
        choices=codegen.LLM_MODES,
    )
    parser.add_argument("--model", default=None)
    parser.add_argument("--game-dir", type=Path, default=DEFAULT_GAME_DIR)
    parser.add_argument("--game-config", type=Path, default=DEFAULT_GAME_CONFIG)
    parser.add_argument("--state-path", type=Path, default=system_map.DEFAULT_PATH)
    parser.add_argument("--baseline", type=Path, default=codegen.DEFAULT_BASELINE_PATH)
    parser.add_argument(
        "--from-vault",
        action="store_true",
        help="auto-derive goals by walking vault/<kind>/*.md (ignores positional goals)",
    )
    parser.add_argument(
        "--from-systems",
        action="store_true",
        help=(
            "auto-derive goals from `chosen_engine.systems` (Phase 3 gameplay "
            "systems). Use after `--from-vault` has produced entity leaves."
        ),
    )
    parser.add_argument("--vault-dir", type=Path, default=_REPO_ROOT / "vault")
    parser.add_argument(
        "--kinds",
        default=None,
        help="with --from-vault, comma-separated kind dirs to include (default: all)",
    )
    parser.add_argument(
        "--systems",
        default=None,
        help="with --from-systems, comma-separated system names to include (default: all)",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="max goals to actually attempt this run (skipped ones do not count)",
    )
    parser.add_argument(
        "--concurrency",
        type=int,
        default=1,
        help=(
            "run codegen for upcoming turns in parallel batches of this size "
            "(default 1 = sequential). The cargo gate still runs serially; each "
            "worker loads its own embedder, so bound this by available memory."
        ),
    )
    parser.add_argument(
        "--repair-attempts",
        type=int,
        default=2,
        help=(
            "on a build failure, re-generate the turn this many times with the "
            "build error fed back before recording pending (default 2; 0 disables)"
        ),
    )
    parser.add_argument(
        "--fallback-llm-mode",
        default=None,
        choices=codegen.LLM_MODES,
        help=(
            "if the primary backend raises (e.g. codex CLI init crash), retry "
            "the turn with this backend before recording pending. Engine- and "
            "backend-agnostic; activates on any exception from --llm-mode."
        ),
    )
    parser.add_argument(
        "--fallback-model",
        default=None,
        help="model id for the fallback backend (defaults to pipeline.config.toml)",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")

    if args.from_vault:
        kinds = [k.strip() for k in args.kinds.split(",") if k.strip()] if args.kinds else None
        valid_kinds = load_valid_kinds(args.game_config)
        goals = derive_goals_from_vault(args.vault_dir, kinds, valid_kinds)
        if not goals:
            allowed = sorted(valid_kinds) if valid_kinds else "all"
            print(
                f"error: no vault notes under {args.vault_dir} "
                f"(kinds={kinds}, valid kinds from game-config={allowed})",
                file=sys.stderr,
            )
            return 2
    elif args.from_systems:
        names = [n.strip() for n in args.systems.split(",") if n.strip()] if args.systems else None
        systems = load_systems(args.game_config)
        goals = derive_goals_from_systems(systems, names)
        if not goals:
            print(
                "error: no systems defined in game-config.json "
                "(chosen_engine.systems is empty; run Phase 0 to populate).",
                file=sys.stderr,
            )
            return 2
    else:
        goals = load_goals(args.goals_file, args.goals)
        if not goals:
            print(
                "error: no goals (pass positional args, --goals-file, "
                "--from-vault, or --from-systems)",
                file=sys.stderr,
            )
            return 2

    results = run_loop(
        goals,
        game_dir=args.game_dir,
        state_path=args.state_path,
        baseline_path=args.baseline,
        llm_mode=args.llm_mode,
        model=args.model,
        error_budget=args.error_budget,
        registration=load_module_registration(args.game_config),
        entrypoint_config=load_entrypoint_config(args.game_config),
        max_turns=args.limit,
        concurrency=args.concurrency,
        repair_attempts=args.repair_attempts,
        smoke_runner=run_cargo_smoke,
        fallback_llm_mode=args.fallback_llm_mode,
        fallback_model=args.fallback_model,
    )

    counts: dict[str, int] = {}
    for r in results:
        counts[r.status] = counts.get(r.status, 0) + 1
        print(_format_result(r))
    print(f"\nsummary: {counts}")
    return 0 if counts.get("pending", 0) == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
