// AUTO-GENERATED by phase2/entrypoint.py. Do not edit by hand.
// Regenerated at the end of every loop_driver.py run from the set of
// `impl Plugin for X` declarations found under src/. Hand-edits will be
// overwritten on the next run; add or remove plugins by writing the
// corresponding leaf modules instead.


use bevy::prelude::*;

use crate::scrap_items::airhorn::AirhornPlugin;
use crate::scrap_items::apparatus::ApparatusPlugin;
use crate::harmless_entity_pages::backwater_gunkfish::BackwaterGunkfishPlugin;
use crate::indoor_entity_pages::barber::BarberPlugin;
use crate::scrap_items::bee_hive::BeeHivePlugin;
use crate::entity_pages::bestiary::BestiaryPlugin;
use crate::scrap_items::bone::BonePlugin;
use crate::indoor_entity_pages::bracken::BrackenPlugin;
use crate::scrap_items::brass_bell::BrassBellPlugin;
use crate::indoor_entity_pages::bunker_spider::BunkerSpiderPlugin;
use crate::indoor_entity_pages::butler::ButlerPlugin;
use crate::outdoor_entity_pages::cadaver_bloom::CadaverBloomPlugin;
use crate::indoor_entity_pages::cadaver::CadaverPlugin;
use crate::scrap_items::cash_register::CashRegisterPlugin;
use crate::gameplay_mechanics::cause_of_death::CauseOfDeathPlugin;
use crate::scrap_items::chemical_jug::ChemicalJugPlugin;
use crate::daytime_entity_pages::circuit_bee::CircuitBeePlugin;
use crate::scrap_items::clock::ClockPlugin;
use crate::scrap_items::clown_horn::ClownHornPlugin;
use crate::scrap_items::coffee_mug::CoffeeMugPlugin;
use crate::indoor_entity_pages::coil_head::CoilHeadPlugin;
use crate::gameplay_mechanics::company_ranks::CompanyRanksPlugin;
use crate::scrap_items::control_pad::ControlPadPlugin;
use crate::scrap_items::cookie_pan::CookiePanPlugin;
use crate::gameplay_mechanics::credits::CreditsPlugin;
use crate::scrap_items::dramatic_mask::DramaticMaskPlugin;
use crate::gameplay_mechanics::dropship::DropshipPlugin;
use crate::scrap_items::dust_pan::DustPanPlugin;
use crate::scrap_items::ear::EarPlugin;
use crate::outdoor_entity_pages::earth_leviathan::EarthLeviathanPlugin;
use crate::scrap_items::egg_beater::EggBeaterPlugin;
use crate::scrap_items::egg::EggPlugin;
use crate::gameplay_mechanics::electric_coil::ElectricCoilPlugin;
use crate::gameplay_mechanics::employee::EmployeePlugin;
use crate::entity_pages::entity::EntityPlugin;
use crate::gameplay_mechanics::entity_targeting::EntityTargetingPlugin;
use crate::outdoor_entity_pages::eyeless_dog::EyelessDogPlugin;
use crate::scrap_items::fancy_lamp::FancyLampPlugin;
use crate::gameplay_mechanics::fear::FearPlugin;
use crate::outdoor_entity_pages::feiopar::FeioparPlugin;
use crate::gameplay_mechanics::fire_exit::FireExitPlugin;
use crate::scrap_items::foot::FootPlugin;
use crate::outdoor_entity_pages::forest_keeper::ForestKeeperPlugin;
use crate::scrap_items::garbage_lid::GarbageLidPlugin;
use crate::indoor_entity_pages::ghost_girl::GhostGirlPlugin;
use crate::daytime_entity_pages::giant_sapsucker::GiantSapsuckerPlugin;
use crate::gameplay_mechanics::global_game_variables::GlobalGameVariablesPlugin;
use crate::scrap_items::golden_cup::GoldenCupPlugin;
use crate::scrap_items::hairdryer::HairdryerPlugin;
use crate::scrap_items::hand::HandPlugin;
use crate::scrap_items::heart::HeartPlugin;
use crate::indoor_entity_pages::hoarding_bug::HoardingBugPlugin;
use crate::indoor_entity_pages::hygrodere::HygroderePlugin;
use crate::system::input_handler::InputHandlerPlugin;
use crate::gameplay_mechanics::interior::InteriorPlugin;
use crate::gameplay_mechanics::item_bar::ItemBarPlugin;
use crate::indoor_entity_pages::jester::JesterPlugin;
use crate::outdoor_entity_pages::kidnapper_fox::KidnapperFoxPlugin;
use crate::scrap_items::knee::KneePlugin;
use crate::map_hazard_pages::landmine::LandminePlugin;
use crate::scrap_items::laser_pointer::LaserPointerPlugin;
use crate::gameplay_mechanics::lore::LorePlugin;
use crate::scrap_items::magic_7_ball::Magic7BallPlugin;
use crate::scrap_items::magnifying_glass::MagnifyingGlassPlugin;
use crate::indoor_entity_pages::maneater::ManeaterPlugin;
use crate::harmless_entity_pages::manticoil::ManticoilPlugin;
use crate::map_hazard_pages::map_hazards::MapHazardsPlugin;
use crate::indoor_entity_pages::mask_hornets::MaskHornetsPlugin;
use crate::indoor_entity_pages::masked::MaskedPlugin;
use crate::gameplay_mechanics::monitors::MonitorsPlugin;
use crate::indoor_entity_pages::nutcrackers::NutcrackersPlugin;
use crate::outdoor_entity_pages::old_bird::OldBirdPlugin;
use crate::gameplay_mechanics::orbit::OrbitPlugin;
use crate::gameplay_mechanics::profit_quota::ProfitQuotaPlugin;
use crate::harmless_entity_pages::roaming_locust::RoamingLocustPlugin;
use crate::scrap_items::rubber_ducky::RubberDuckyPlugin;
use crate::gameplay_mechanics::scanner::ScannerPlugin;
use crate::sim::SimChecksumPlugin;
use crate::sim::SimEventsPlugin;
use crate::event_pages::single_item_day::SingleItemDayPlugin;
use crate::indoor_entity_pages::snare_flea::SnareFleaPlugin;
use crate::map_hazard_pages::spike_trap::SpikeTrapPlugin;
use crate::indoor_entity_pages::spore_lizard::SporeLizardPlugin;
use crate::gameplay_mechanics::terminal::TerminalPlugin;
use crate::entity_pages::the_company_monster::TheCompanyMonsterPlugin;
use crate::gameplay_mechanics::the_ship::TheShipPlugin;
use crate::indoor_entity_pages::thumper::ThumperPlugin;
use crate::harmless_entity_pages::tulip_snake::TulipSnakePlugin;
use crate::map_hazard_pages::turret::TurretPlugin;
use crate::harmless_entity_pages::vain_shroud::VainShroudPlugin;
use crate::gameplay_mechanics::weather::WeatherPlugin;

/// Register every plugin discovered under `src/`.
///
/// Generated by `phase2/entrypoint.py` at the end of each loop_driver
/// run. The caller still owns `DefaultPlugins`, window config, camera
/// spawning, and any per-engine resources that vary per binary.
pub fn add_all(app: &mut App) -> &mut App {
    app
        .add_plugins((AirhornPlugin, ApparatusPlugin, BackwaterGunkfishPlugin, BarberPlugin, BeeHivePlugin, BestiaryPlugin, BonePlugin, BrackenPlugin, BrassBellPlugin, BunkerSpiderPlugin, ButlerPlugin, CadaverBloomPlugin, CadaverPlugin, CashRegisterPlugin))
        .add_plugins((CauseOfDeathPlugin, ChemicalJugPlugin, CircuitBeePlugin, ClockPlugin, ClownHornPlugin, CoffeeMugPlugin, CoilHeadPlugin, CompanyRanksPlugin, ControlPadPlugin, CookiePanPlugin, CreditsPlugin, DramaticMaskPlugin, DropshipPlugin, DustPanPlugin))
        .add_plugins((EarPlugin, EarthLeviathanPlugin, EggBeaterPlugin, EggPlugin, ElectricCoilPlugin, EmployeePlugin, EntityPlugin, EntityTargetingPlugin, EyelessDogPlugin, FancyLampPlugin, FearPlugin, FeioparPlugin, FireExitPlugin, FootPlugin))
        .add_plugins((ForestKeeperPlugin, GarbageLidPlugin, GhostGirlPlugin, GiantSapsuckerPlugin, GlobalGameVariablesPlugin, GoldenCupPlugin, HairdryerPlugin, HandPlugin, HeartPlugin, HoardingBugPlugin, HygroderePlugin, InputHandlerPlugin, InteriorPlugin, ItemBarPlugin))
        .add_plugins((JesterPlugin, KidnapperFoxPlugin, KneePlugin, LandminePlugin, LaserPointerPlugin, LorePlugin, Magic7BallPlugin, MagnifyingGlassPlugin, ManeaterPlugin, ManticoilPlugin, MapHazardsPlugin, MaskHornetsPlugin, MaskedPlugin, MonitorsPlugin))
        .add_plugins((NutcrackersPlugin, OldBirdPlugin, OrbitPlugin, ProfitQuotaPlugin, RoamingLocustPlugin, RubberDuckyPlugin, ScannerPlugin, SimChecksumPlugin, SimEventsPlugin, SingleItemDayPlugin, SnareFleaPlugin, SpikeTrapPlugin, SporeLizardPlugin, TerminalPlugin))
        .add_plugins((TheCompanyMonsterPlugin, TheShipPlugin, ThumperPlugin, TulipSnakePlugin, TurretPlugin, VainShroudPlugin, WeatherPlugin))
}
