// Visual entrypoint for the generated crate. Scaffold-rendered by
// `phase2/scaffold.py` — engine-specific but game-agnostic. Per-game content
// (units, buildings, etc.) flows in through `clone_game::app_plugins::add_all`,
// which is regenerated by `phase2/entrypoint.py` on every loop turn from the
// `impl Plugin for X` declarations under `src/`.
//
// Cold start (no plugins yet): the window opens, the camera spawns, a small
// set of colored demo sprites flag that the renderer is alive, the sim ticks
// at 25Hz, and the checksum log fires every 25 ticks. As the codegen loop
// produces plugins, they auto-register here without any edit to this file.
//
// Any entity that carries `clone_game::sim::SimPosition` is mirrored into a
// Bevy `Transform` every render frame, so generated unit plugins become
// visible as soon as a system spawns them with both a `SimPosition` and a
// `Sprite`.

use bevy::prelude::*;
use clone_game::app_plugins;
use clone_game::sim::{GameSeed, SimChecksumState, SimHz, SimPosition, SimTick};
use fixed::types::I32F32;

const SIM_FIXED_HZ: f64 = 25.0;
const CHECKSUM_LOG_PERIOD_TICKS: u64 = 25;
const WINDOW_TITLE: &str = "cloneGame — generated Bevy crate";
const DEMO_SPRITE_SIZE: f32 = 32.0;

fn main() {
    let mut app = App::new();
    app.insert_resource(ClearColor(Color::srgb(0.05, 0.07, 0.10)))
        .add_plugins(DefaultPlugins.set(WindowPlugin {
            primary_window: Some(Window {
                title: WINDOW_TITLE.into(),
                resolution: (1280.0, 720.0).into(),
                ..default()
            }),
            ..default()
        }))
        .insert_resource(Time::<Fixed>::from_hz(SIM_FIXED_HZ))
        .insert_resource(GameSeed(0xC10E_6A3E_DEAD_BEEF))
        .insert_resource(SimTick::default())
        .insert_resource(SimHz::default());
    app_plugins::add_all(&mut app);
    app.add_systems(Startup, (spawn_camera, spawn_demo_sprites))
        .add_systems(FixedUpdate, advance_sim_tick)
        .add_systems(FixedUpdate, log_checksum_periodically)
        .add_systems(Update, sync_sim_position_to_transform)
        .run();
}

fn spawn_camera(mut commands: Commands) {
    commands.spawn(Camera2d);
}

/// Spawn a small grid of colored squares so the operator can see the window
/// is alive on cold start, before any game plugin spawns anything. Per-game
/// spawning (units / buildings / etc.) is the responsibility of generated
/// plugins; this scaffold spawn just proves the renderer + camera + transform
/// mirror are wired correctly.
fn spawn_demo_sprites(mut commands: Commands) {
    let palette = [
        Color::srgb(0.85, 0.20, 0.20),
        Color::srgb(0.95, 0.75, 0.20),
        Color::srgb(0.30, 0.85, 0.40),
        Color::srgb(0.25, 0.60, 0.95),
        Color::srgb(0.75, 0.40, 0.90),
    ];
    for (i, color) in palette.iter().enumerate() {
        let x = -120.0 + (i as f32) * 60.0;
        commands.spawn((
            Sprite {
                color: *color,
                custom_size: Some(Vec2::splat(DEMO_SPRITE_SIZE)),
                ..default()
            },
            Transform::from_xyz(x, 0.0, 0.0),
            SimPosition {
                x: I32F32::from_num(x),
                y: I32F32::ZERO,
            },
        ));
    }
}

fn advance_sim_tick(mut tick: ResMut<SimTick>) {
    tick.0 = tick.0.wrapping_add(1);
}

fn log_checksum_periodically(tick: Res<SimTick>, checksum: Res<SimChecksumState>) {
    if tick.0 > 0 && tick.0 % CHECKSUM_LOG_PERIOD_TICKS == 0 {
        info!("sim_tick={} checksum=0x{:016x}", tick.0, checksum.hash);
    }
}

/// Mirror every entity's fixed-point `SimPosition` onto its render-side
/// `Transform.translation`. Conversion is one-way: the sim authoritative,
/// render reads. Runs in `Update`, so the window stays at vsync rate even
/// when the sim ticks at 25Hz. Any new generated unit that spawns with a
/// `SimPosition` becomes visible automatically the moment a `Sprite` (or
/// `Mesh2d`) is attached.
fn sync_sim_position_to_transform(mut query: Query<(&SimPosition, &mut Transform)>) {
    for (pos, mut transform) in &mut query {
        transform.translation.x = pos.x.to_num::<f32>();
        transform.translation.y = pos.y.to_num::<f32>();
    }
}
